name: Build & Test

on: [push, pull_request]

jobs:
  Ubuntu-2004-gcc:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    env:
      MRUBY_CONFIG: ci/gcc-clang
      CC: gcc
    steps:
      - uses: actions/checkout@v2
      - name: Ruby version
        run: ruby -v
      - name: Compiler version
        run: ${{ env.CC }} --version
      - name: Build and test
        run: rake -m test:build && rake test:run

  Ubuntu-2004-clang:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    env:
      MRUBY_CONFIG: ci/gcc-clang
      CC: clang
    steps:
      - uses: actions/checkout@v2
      - name: Ruby version
        run: ruby -v
      - name: Compiler version
        run: ${{ env.CC }} --version
      - name: Build and test
        run: rake -m test:build && rake test:run

  macOS:
    runs-on: macos-latest
    timeout-minutes: 10
    env:
      MRUBY_CONFIG: ci/gcc-clang
      CC: clang
    steps:
      - uses: actions/checkout@v2
      - name: Ruby version
        run: ruby -v
      - name: Compiler version
        run: ${{ env.CC }} --version
      - name: Build and test
        run: rake -m test:build && rake test:run
